version: '3'
services:
  fastdfs:
    build: .
    image: qbanxiaoli/fastdfs
    # 该容器是否需要开机启动+自动重启。若需要，则取消注释。
    restart: always
    container_name: fastdfs
    ports:
    - 80:80
    - 22122:22122
    - 23000:23000
    environment:
      # nginx服务端口,默认80端口，可修改
      WEB_PORT: 80
      # tracker_server服务端口，默认22122端口，可修改
      FDFS_PORT: 22122
      # storage_server服务端口，默认23000端口，可修改
      STORAGE_PORT: 23000
      # fastdht服务端口，默认11411端口，可修改
      FDHT_PORT: 11411
      # docker所在宿主机IP内网地址，默认使用eth0网卡的地址
      IP: 192.168.0.105
    volumes:
    # 将本地目录映射到docker容器内的fastdfs数据存储目录，将fastdfs文件存储到主机上，以免每次重建docker容器，之前存储的文件就丢失了。
    - ~/fastdfs:/var/local
    # 由于windows和unix识别不了host网络，目前需要新建网段，强制指定容器ip与宿主机ip一致
    networks:
      fastdfs_net:
        ipv4_address: 192.168.0.105

networks: 
  fastdfs_net:
    driver: bridge
    ipam:
      config:
      - subnet: 192.168.0.0/24
